// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: util.proto

#include "util.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_util_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_util_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_GeneratorOutput_FilesEntry_DoNotUse;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_util_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_LanguageDescription;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_util_2eproto ::google::protobuf::internal::SCCInfo<1> scc_info_LanguageList_LanguagesEntry_DoNotUse;
}  // namespace protobuf_util_2eproto
namespace google {
namespace protobuf {
namespace compiler {
namespace wasm {
namespace util {
class GeneratorInputDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GeneratorInput>
      _instance;
} _GeneratorInput_default_instance_;
class GeneratorOutput_FilesEntry_DoNotUseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GeneratorOutput_FilesEntry_DoNotUse>
      _instance;
} _GeneratorOutput_FilesEntry_DoNotUse_default_instance_;
class GeneratorOutputDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<GeneratorOutput>
      _instance;
} _GeneratorOutput_default_instance_;
class LanguageDescriptionDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<LanguageDescription>
      _instance;
} _LanguageDescription_default_instance_;
class LanguageList_LanguagesEntry_DoNotUseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<LanguageList_LanguagesEntry_DoNotUse>
      _instance;
} _LanguageList_LanguagesEntry_DoNotUse_default_instance_;
class LanguageListDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<LanguageList>
      _instance;
} _LanguageList_default_instance_;
}  // namespace util
}  // namespace wasm
}  // namespace compiler
}  // namespace protobuf
}  // namespace google
namespace protobuf_util_2eproto {
static void InitDefaultsGeneratorInput() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::google::protobuf::compiler::wasm::util::_GeneratorInput_default_instance_;
    new (ptr) ::google::protobuf::compiler::wasm::util::GeneratorInput();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::google::protobuf::compiler::wasm::util::GeneratorInput::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_GeneratorInput =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsGeneratorInput}, {}};

static void InitDefaultsGeneratorOutput_FilesEntry_DoNotUse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::google::protobuf::compiler::wasm::util::_GeneratorOutput_FilesEntry_DoNotUse_default_instance_;
    new (ptr) ::google::protobuf::compiler::wasm::util::GeneratorOutput_FilesEntry_DoNotUse();
  }
  ::google::protobuf::compiler::wasm::util::GeneratorOutput_FilesEntry_DoNotUse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_GeneratorOutput_FilesEntry_DoNotUse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsGeneratorOutput_FilesEntry_DoNotUse}, {}};

static void InitDefaultsGeneratorOutput() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::google::protobuf::compiler::wasm::util::_GeneratorOutput_default_instance_;
    new (ptr) ::google::protobuf::compiler::wasm::util::GeneratorOutput();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::google::protobuf::compiler::wasm::util::GeneratorOutput::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_GeneratorOutput =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsGeneratorOutput}, {
      &protobuf_util_2eproto::scc_info_GeneratorOutput_FilesEntry_DoNotUse.base,}};

static void InitDefaultsLanguageDescription() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::google::protobuf::compiler::wasm::util::_LanguageDescription_default_instance_;
    new (ptr) ::google::protobuf::compiler::wasm::util::LanguageDescription();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::google::protobuf::compiler::wasm::util::LanguageDescription::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_LanguageDescription =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsLanguageDescription}, {}};

static void InitDefaultsLanguageList_LanguagesEntry_DoNotUse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::google::protobuf::compiler::wasm::util::_LanguageList_LanguagesEntry_DoNotUse_default_instance_;
    new (ptr) ::google::protobuf::compiler::wasm::util::LanguageList_LanguagesEntry_DoNotUse();
  }
  ::google::protobuf::compiler::wasm::util::LanguageList_LanguagesEntry_DoNotUse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_LanguageList_LanguagesEntry_DoNotUse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsLanguageList_LanguagesEntry_DoNotUse}, {
      &protobuf_util_2eproto::scc_info_LanguageDescription.base,}};

static void InitDefaultsLanguageList() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::google::protobuf::compiler::wasm::util::_LanguageList_default_instance_;
    new (ptr) ::google::protobuf::compiler::wasm::util::LanguageList();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::google::protobuf::compiler::wasm::util::LanguageList::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_LanguageList =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsLanguageList}, {
      &protobuf_util_2eproto::scc_info_LanguageList_LanguagesEntry_DoNotUse.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_GeneratorInput.base);
  ::google::protobuf::internal::InitSCC(&scc_info_GeneratorOutput_FilesEntry_DoNotUse.base);
  ::google::protobuf::internal::InitSCC(&scc_info_GeneratorOutput.base);
  ::google::protobuf::internal::InitSCC(&scc_info_LanguageDescription.base);
  ::google::protobuf::internal::InitSCC(&scc_info_LanguageList_LanguagesEntry_DoNotUse.base);
  ::google::protobuf::internal::InitSCC(&scc_info_LanguageList.base);
}

::google::protobuf::Metadata file_level_metadata[6];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobuf::compiler::wasm::util::GeneratorInput, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobuf::compiler::wasm::util::GeneratorInput, name_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobuf::compiler::wasm::util::GeneratorInput, content_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobuf::compiler::wasm::util::GeneratorInput, language_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobuf::compiler::wasm::util::GeneratorInput, parameters_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobuf::compiler::wasm::util::GeneratorOutput_FilesEntry_DoNotUse, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobuf::compiler::wasm::util::GeneratorOutput_FilesEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobuf::compiler::wasm::util::GeneratorOutput_FilesEntry_DoNotUse, key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobuf::compiler::wasm::util::GeneratorOutput_FilesEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobuf::compiler::wasm::util::GeneratorOutput, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobuf::compiler::wasm::util::GeneratorOutput, error_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobuf::compiler::wasm::util::GeneratorOutput, files_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobuf::compiler::wasm::util::LanguageDescription, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobuf::compiler::wasm::util::LanguageDescription, protoc_output_flag_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobuf::compiler::wasm::util::LanguageDescription, protoc_option_flag_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobuf::compiler::wasm::util::LanguageList_LanguagesEntry_DoNotUse, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobuf::compiler::wasm::util::LanguageList_LanguagesEntry_DoNotUse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobuf::compiler::wasm::util::LanguageList_LanguagesEntry_DoNotUse, key_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobuf::compiler::wasm::util::LanguageList_LanguagesEntry_DoNotUse, value_),
  0,
  1,
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobuf::compiler::wasm::util::LanguageList, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::google::protobuf::compiler::wasm::util::LanguageList, languages_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::google::protobuf::compiler::wasm::util::GeneratorInput)},
  { 9, 16, sizeof(::google::protobuf::compiler::wasm::util::GeneratorOutput_FilesEntry_DoNotUse)},
  { 18, -1, sizeof(::google::protobuf::compiler::wasm::util::GeneratorOutput)},
  { 25, -1, sizeof(::google::protobuf::compiler::wasm::util::LanguageDescription)},
  { 32, 39, sizeof(::google::protobuf::compiler::wasm::util::LanguageList_LanguagesEntry_DoNotUse)},
  { 41, -1, sizeof(::google::protobuf::compiler::wasm::util::LanguageList)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::google::protobuf::compiler::wasm::util::_GeneratorInput_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::google::protobuf::compiler::wasm::util::_GeneratorOutput_FilesEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::google::protobuf::compiler::wasm::util::_GeneratorOutput_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::google::protobuf::compiler::wasm::util::_LanguageDescription_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::google::protobuf::compiler::wasm::util::_LanguageList_LanguagesEntry_DoNotUse_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::google::protobuf::compiler::wasm::util::_LanguageList_default_instance_),
};

static void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "util.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

static void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 6);
}

static void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\nutil.proto\022\"google.protobuf.compiler.w"
      "asm.util\"U\n\016GeneratorInput\022\014\n\004name\030\001 \001(\t"
      "\022\017\n\007content\030\002 \001(\t\022\020\n\010language\030\003 \001(\t\022\022\n\np"
      "arameters\030\004 \001(\t\"\235\001\n\017GeneratorOutput\022\r\n\005e"
      "rror\030\001 \001(\t\022M\n\005files\030\002 \003(\0132>.google.proto"
      "buf.compiler.wasm.util.GeneratorOutput.F"
      "ilesEntry\032,\n\nFilesEntry\022\013\n\003key\030\001 \001(\t\022\r\n\005"
      "value\030\002 \001(\t:\0028\001\"M\n\023LanguageDescription\022\032"
      "\n\022protoc_output_flag\030\001 \001(\t\022\032\n\022protoc_opt"
      "ion_flag\030\002 \001(\t\"\315\001\n\014LanguageList\022R\n\tlangu"
      "ages\030\001 \003(\0132\?.google.protobuf.compiler.wa"
      "sm.util.LanguageList.LanguagesEntry\032i\n\016L"
      "anguagesEntry\022\013\n\003key\030\001 \001(\t\022F\n\005value\030\002 \001("
      "\01327.google.protobuf.compiler.wasm.util.L"
      "anguageDescription:\0028\001b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 590);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "util.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_util_2eproto
namespace google {
namespace protobuf {
namespace compiler {
namespace wasm {
namespace util {

// ===================================================================

void GeneratorInput::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GeneratorInput::kNameFieldNumber;
const int GeneratorInput::kContentFieldNumber;
const int GeneratorInput::kLanguageFieldNumber;
const int GeneratorInput::kParametersFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GeneratorInput::GeneratorInput()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_util_2eproto::scc_info_GeneratorInput.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.protobuf.compiler.wasm.util.GeneratorInput)
}
GeneratorInput::GeneratorInput(const GeneratorInput& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.name().size() > 0) {
    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  content_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.content().size() > 0) {
    content_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.content_);
  }
  language_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.language().size() > 0) {
    language_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.language_);
  }
  parameters_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.parameters().size() > 0) {
    parameters_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.parameters_);
  }
  // @@protoc_insertion_point(copy_constructor:google.protobuf.compiler.wasm.util.GeneratorInput)
}

void GeneratorInput::SharedCtor() {
  name_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  content_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  language_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  parameters_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

GeneratorInput::~GeneratorInput() {
  // @@protoc_insertion_point(destructor:google.protobuf.compiler.wasm.util.GeneratorInput)
  SharedDtor();
}

void GeneratorInput::SharedDtor() {
  name_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  content_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  language_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  parameters_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void GeneratorInput::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* GeneratorInput::descriptor() {
  ::protobuf_util_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_util_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GeneratorInput& GeneratorInput::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_util_2eproto::scc_info_GeneratorInput.base);
  return *internal_default_instance();
}


void GeneratorInput::Clear() {
// @@protoc_insertion_point(message_clear_start:google.protobuf.compiler.wasm.util.GeneratorInput)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  name_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  content_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  language_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  parameters_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool GeneratorInput::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:google.protobuf.compiler.wasm.util.GeneratorInput)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string name = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_name()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->name().data(), static_cast<int>(this->name().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.protobuf.compiler.wasm.util.GeneratorInput.name"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string content = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_content()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->content().data(), static_cast<int>(this->content().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.protobuf.compiler.wasm.util.GeneratorInput.content"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string language = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_language()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->language().data(), static_cast<int>(this->language().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.protobuf.compiler.wasm.util.GeneratorInput.language"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string parameters = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_parameters()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->parameters().data(), static_cast<int>(this->parameters().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.protobuf.compiler.wasm.util.GeneratorInput.parameters"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:google.protobuf.compiler.wasm.util.GeneratorInput)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.protobuf.compiler.wasm.util.GeneratorInput)
  return false;
#undef DO_
}

void GeneratorInput::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.protobuf.compiler.wasm.util.GeneratorInput)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.compiler.wasm.util.GeneratorInput.name");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->name(), output);
  }

  // string content = 2;
  if (this->content().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->content().data(), static_cast<int>(this->content().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.compiler.wasm.util.GeneratorInput.content");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->content(), output);
  }

  // string language = 3;
  if (this->language().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->language().data(), static_cast<int>(this->language().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.compiler.wasm.util.GeneratorInput.language");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->language(), output);
  }

  // string parameters = 4;
  if (this->parameters().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->parameters().data(), static_cast<int>(this->parameters().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.compiler.wasm.util.GeneratorInput.parameters");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->parameters(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:google.protobuf.compiler.wasm.util.GeneratorInput)
}

::google::protobuf::uint8* GeneratorInput::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:google.protobuf.compiler.wasm.util.GeneratorInput)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string name = 1;
  if (this->name().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->name().data(), static_cast<int>(this->name().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.compiler.wasm.util.GeneratorInput.name");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->name(), target);
  }

  // string content = 2;
  if (this->content().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->content().data(), static_cast<int>(this->content().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.compiler.wasm.util.GeneratorInput.content");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->content(), target);
  }

  // string language = 3;
  if (this->language().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->language().data(), static_cast<int>(this->language().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.compiler.wasm.util.GeneratorInput.language");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->language(), target);
  }

  // string parameters = 4;
  if (this->parameters().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->parameters().data(), static_cast<int>(this->parameters().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.compiler.wasm.util.GeneratorInput.parameters");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->parameters(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.protobuf.compiler.wasm.util.GeneratorInput)
  return target;
}

size_t GeneratorInput::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.protobuf.compiler.wasm.util.GeneratorInput)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string name = 1;
  if (this->name().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->name());
  }

  // string content = 2;
  if (this->content().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->content());
  }

  // string language = 3;
  if (this->language().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->language());
  }

  // string parameters = 4;
  if (this->parameters().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->parameters());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GeneratorInput::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.protobuf.compiler.wasm.util.GeneratorInput)
  GOOGLE_DCHECK_NE(&from, this);
  const GeneratorInput* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GeneratorInput>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.protobuf.compiler.wasm.util.GeneratorInput)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.protobuf.compiler.wasm.util.GeneratorInput)
    MergeFrom(*source);
  }
}

void GeneratorInput::MergeFrom(const GeneratorInput& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.protobuf.compiler.wasm.util.GeneratorInput)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.name().size() > 0) {

    name_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.name_);
  }
  if (from.content().size() > 0) {

    content_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.content_);
  }
  if (from.language().size() > 0) {

    language_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.language_);
  }
  if (from.parameters().size() > 0) {

    parameters_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.parameters_);
  }
}

void GeneratorInput::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.protobuf.compiler.wasm.util.GeneratorInput)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GeneratorInput::CopyFrom(const GeneratorInput& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.protobuf.compiler.wasm.util.GeneratorInput)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GeneratorInput::IsInitialized() const {
  return true;
}

void GeneratorInput::Swap(GeneratorInput* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GeneratorInput::InternalSwap(GeneratorInput* other) {
  using std::swap;
  name_.Swap(&other->name_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  content_.Swap(&other->content_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  language_.Swap(&other->language_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  parameters_.Swap(&other->parameters_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata GeneratorInput::GetMetadata() const {
  protobuf_util_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_util_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

GeneratorOutput_FilesEntry_DoNotUse::GeneratorOutput_FilesEntry_DoNotUse() {}
GeneratorOutput_FilesEntry_DoNotUse::GeneratorOutput_FilesEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
void GeneratorOutput_FilesEntry_DoNotUse::MergeFrom(const GeneratorOutput_FilesEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::google::protobuf::Metadata GeneratorOutput_FilesEntry_DoNotUse::GetMetadata() const {
  ::protobuf_util_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_util_2eproto::file_level_metadata[1];
}
void GeneratorOutput_FilesEntry_DoNotUse::MergeFrom(
    const ::google::protobuf::Message& other) {
  ::google::protobuf::Message::MergeFrom(other);
}


// ===================================================================

void GeneratorOutput::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int GeneratorOutput::kErrorFieldNumber;
const int GeneratorOutput::kFilesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

GeneratorOutput::GeneratorOutput()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_util_2eproto::scc_info_GeneratorOutput.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.protobuf.compiler.wasm.util.GeneratorOutput)
}
GeneratorOutput::GeneratorOutput(const GeneratorOutput& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  files_.MergeFrom(from.files_);
  error_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.error().size() > 0) {
    error_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.error_);
  }
  // @@protoc_insertion_point(copy_constructor:google.protobuf.compiler.wasm.util.GeneratorOutput)
}

void GeneratorOutput::SharedCtor() {
  error_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

GeneratorOutput::~GeneratorOutput() {
  // @@protoc_insertion_point(destructor:google.protobuf.compiler.wasm.util.GeneratorOutput)
  SharedDtor();
}

void GeneratorOutput::SharedDtor() {
  error_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void GeneratorOutput::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* GeneratorOutput::descriptor() {
  ::protobuf_util_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_util_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const GeneratorOutput& GeneratorOutput::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_util_2eproto::scc_info_GeneratorOutput.base);
  return *internal_default_instance();
}


void GeneratorOutput::Clear() {
// @@protoc_insertion_point(message_clear_start:google.protobuf.compiler.wasm.util.GeneratorOutput)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  files_.Clear();
  error_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool GeneratorOutput::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:google.protobuf.compiler.wasm.util.GeneratorOutput)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string error = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_error()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->error().data(), static_cast<int>(this->error().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.protobuf.compiler.wasm.util.GeneratorOutput.error"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // map<string, string> files = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          GeneratorOutput_FilesEntry_DoNotUse::Parser< ::google::protobuf::internal::MapField<
              GeneratorOutput_FilesEntry_DoNotUse,
              ::std::string, ::std::string,
              ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
              ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
              0 >,
            ::google::protobuf::Map< ::std::string, ::std::string > > parser(&files_);
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
              input, &parser));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            parser.key().data(), static_cast<int>(parser.key().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.protobuf.compiler.wasm.util.GeneratorOutput.FilesEntry.key"));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            parser.value().data(), static_cast<int>(parser.value().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.protobuf.compiler.wasm.util.GeneratorOutput.FilesEntry.value"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:google.protobuf.compiler.wasm.util.GeneratorOutput)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.protobuf.compiler.wasm.util.GeneratorOutput)
  return false;
#undef DO_
}

void GeneratorOutput::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.protobuf.compiler.wasm.util.GeneratorOutput)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string error = 1;
  if (this->error().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->error().data(), static_cast<int>(this->error().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.compiler.wasm.util.GeneratorOutput.error");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->error(), output);
  }

  // map<string, string> files = 2;
  if (!this->files().empty()) {
    typedef ::google::protobuf::Map< ::std::string, ::std::string >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::google::protobuf::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "google.protobuf.compiler.wasm.util.GeneratorOutput.FilesEntry.key");
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->second.data(), static_cast<int>(p->second.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "google.protobuf.compiler.wasm.util.GeneratorOutput.FilesEntry.value");
      }
    };

    if (output->IsSerializationDeterministic() &&
        this->files().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->files().size()]);
      typedef ::google::protobuf::Map< ::std::string, ::std::string >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->files().begin();
          it != this->files().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::std::unique_ptr<GeneratorOutput_FilesEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(files_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            2, *entry, output);
        Utf8Check::Check(items[static_cast<ptrdiff_t>(i)]);
      }
    } else {
      ::std::unique_ptr<GeneratorOutput_FilesEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->files().begin();
          it != this->files().end(); ++it) {
        entry.reset(files_.NewEntryWrapper(
            it->first, it->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            2, *entry, output);
        Utf8Check::Check(&*it);
      }
    }
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:google.protobuf.compiler.wasm.util.GeneratorOutput)
}

::google::protobuf::uint8* GeneratorOutput::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:google.protobuf.compiler.wasm.util.GeneratorOutput)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string error = 1;
  if (this->error().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->error().data(), static_cast<int>(this->error().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.compiler.wasm.util.GeneratorOutput.error");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->error(), target);
  }

  // map<string, string> files = 2;
  if (!this->files().empty()) {
    typedef ::google::protobuf::Map< ::std::string, ::std::string >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::google::protobuf::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "google.protobuf.compiler.wasm.util.GeneratorOutput.FilesEntry.key");
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->second.data(), static_cast<int>(p->second.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "google.protobuf.compiler.wasm.util.GeneratorOutput.FilesEntry.value");
      }
    };

    if (deterministic &&
        this->files().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->files().size()]);
      typedef ::google::protobuf::Map< ::std::string, ::std::string >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->files().begin();
          it != this->files().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::std::unique_ptr<GeneratorOutput_FilesEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(files_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       2, *entry, deterministic, target);
;
        Utf8Check::Check(items[static_cast<ptrdiff_t>(i)]);
      }
    } else {
      ::std::unique_ptr<GeneratorOutput_FilesEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
          it = this->files().begin();
          it != this->files().end(); ++it) {
        entry.reset(files_.NewEntryWrapper(
            it->first, it->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       2, *entry, deterministic, target);
;
        Utf8Check::Check(&*it);
      }
    }
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.protobuf.compiler.wasm.util.GeneratorOutput)
  return target;
}

size_t GeneratorOutput::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.protobuf.compiler.wasm.util.GeneratorOutput)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // map<string, string> files = 2;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->files_size());
  {
    ::std::unique_ptr<GeneratorOutput_FilesEntry_DoNotUse> entry;
    for (::google::protobuf::Map< ::std::string, ::std::string >::const_iterator
        it = this->files().begin();
        it != this->files().end(); ++it) {
      entry.reset(files_.NewEntryWrapper(it->first, it->second));
      total_size += ::google::protobuf::internal::WireFormatLite::
          MessageSizeNoVirtual(*entry);
    }
  }

  // string error = 1;
  if (this->error().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->error());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void GeneratorOutput::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.protobuf.compiler.wasm.util.GeneratorOutput)
  GOOGLE_DCHECK_NE(&from, this);
  const GeneratorOutput* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const GeneratorOutput>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.protobuf.compiler.wasm.util.GeneratorOutput)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.protobuf.compiler.wasm.util.GeneratorOutput)
    MergeFrom(*source);
  }
}

void GeneratorOutput::MergeFrom(const GeneratorOutput& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.protobuf.compiler.wasm.util.GeneratorOutput)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  files_.MergeFrom(from.files_);
  if (from.error().size() > 0) {

    error_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.error_);
  }
}

void GeneratorOutput::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.protobuf.compiler.wasm.util.GeneratorOutput)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void GeneratorOutput::CopyFrom(const GeneratorOutput& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.protobuf.compiler.wasm.util.GeneratorOutput)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool GeneratorOutput::IsInitialized() const {
  return true;
}

void GeneratorOutput::Swap(GeneratorOutput* other) {
  if (other == this) return;
  InternalSwap(other);
}
void GeneratorOutput::InternalSwap(GeneratorOutput* other) {
  using std::swap;
  files_.Swap(&other->files_);
  error_.Swap(&other->error_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata GeneratorOutput::GetMetadata() const {
  protobuf_util_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_util_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void LanguageDescription::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LanguageDescription::kProtocOutputFlagFieldNumber;
const int LanguageDescription::kProtocOptionFlagFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LanguageDescription::LanguageDescription()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_util_2eproto::scc_info_LanguageDescription.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.protobuf.compiler.wasm.util.LanguageDescription)
}
LanguageDescription::LanguageDescription(const LanguageDescription& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  protoc_output_flag_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.protoc_output_flag().size() > 0) {
    protoc_output_flag_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.protoc_output_flag_);
  }
  protoc_option_flag_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.protoc_option_flag().size() > 0) {
    protoc_option_flag_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.protoc_option_flag_);
  }
  // @@protoc_insertion_point(copy_constructor:google.protobuf.compiler.wasm.util.LanguageDescription)
}

void LanguageDescription::SharedCtor() {
  protoc_output_flag_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  protoc_option_flag_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

LanguageDescription::~LanguageDescription() {
  // @@protoc_insertion_point(destructor:google.protobuf.compiler.wasm.util.LanguageDescription)
  SharedDtor();
}

void LanguageDescription::SharedDtor() {
  protoc_output_flag_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  protoc_option_flag_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void LanguageDescription::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* LanguageDescription::descriptor() {
  ::protobuf_util_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_util_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const LanguageDescription& LanguageDescription::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_util_2eproto::scc_info_LanguageDescription.base);
  return *internal_default_instance();
}


void LanguageDescription::Clear() {
// @@protoc_insertion_point(message_clear_start:google.protobuf.compiler.wasm.util.LanguageDescription)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  protoc_output_flag_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  protoc_option_flag_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool LanguageDescription::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:google.protobuf.compiler.wasm.util.LanguageDescription)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string protoc_output_flag = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_protoc_output_flag()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->protoc_output_flag().data(), static_cast<int>(this->protoc_output_flag().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.protobuf.compiler.wasm.util.LanguageDescription.protoc_output_flag"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string protoc_option_flag = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_protoc_option_flag()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->protoc_option_flag().data(), static_cast<int>(this->protoc_option_flag().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.protobuf.compiler.wasm.util.LanguageDescription.protoc_option_flag"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:google.protobuf.compiler.wasm.util.LanguageDescription)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.protobuf.compiler.wasm.util.LanguageDescription)
  return false;
#undef DO_
}

void LanguageDescription::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.protobuf.compiler.wasm.util.LanguageDescription)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string protoc_output_flag = 1;
  if (this->protoc_output_flag().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->protoc_output_flag().data(), static_cast<int>(this->protoc_output_flag().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.compiler.wasm.util.LanguageDescription.protoc_output_flag");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->protoc_output_flag(), output);
  }

  // string protoc_option_flag = 2;
  if (this->protoc_option_flag().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->protoc_option_flag().data(), static_cast<int>(this->protoc_option_flag().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.compiler.wasm.util.LanguageDescription.protoc_option_flag");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->protoc_option_flag(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:google.protobuf.compiler.wasm.util.LanguageDescription)
}

::google::protobuf::uint8* LanguageDescription::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:google.protobuf.compiler.wasm.util.LanguageDescription)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string protoc_output_flag = 1;
  if (this->protoc_output_flag().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->protoc_output_flag().data(), static_cast<int>(this->protoc_output_flag().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.compiler.wasm.util.LanguageDescription.protoc_output_flag");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->protoc_output_flag(), target);
  }

  // string protoc_option_flag = 2;
  if (this->protoc_option_flag().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->protoc_option_flag().data(), static_cast<int>(this->protoc_option_flag().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "google.protobuf.compiler.wasm.util.LanguageDescription.protoc_option_flag");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->protoc_option_flag(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.protobuf.compiler.wasm.util.LanguageDescription)
  return target;
}

size_t LanguageDescription::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.protobuf.compiler.wasm.util.LanguageDescription)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string protoc_output_flag = 1;
  if (this->protoc_output_flag().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->protoc_output_flag());
  }

  // string protoc_option_flag = 2;
  if (this->protoc_option_flag().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->protoc_option_flag());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void LanguageDescription::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.protobuf.compiler.wasm.util.LanguageDescription)
  GOOGLE_DCHECK_NE(&from, this);
  const LanguageDescription* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const LanguageDescription>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.protobuf.compiler.wasm.util.LanguageDescription)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.protobuf.compiler.wasm.util.LanguageDescription)
    MergeFrom(*source);
  }
}

void LanguageDescription::MergeFrom(const LanguageDescription& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.protobuf.compiler.wasm.util.LanguageDescription)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.protoc_output_flag().size() > 0) {

    protoc_output_flag_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.protoc_output_flag_);
  }
  if (from.protoc_option_flag().size() > 0) {

    protoc_option_flag_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.protoc_option_flag_);
  }
}

void LanguageDescription::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.protobuf.compiler.wasm.util.LanguageDescription)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LanguageDescription::CopyFrom(const LanguageDescription& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.protobuf.compiler.wasm.util.LanguageDescription)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LanguageDescription::IsInitialized() const {
  return true;
}

void LanguageDescription::Swap(LanguageDescription* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LanguageDescription::InternalSwap(LanguageDescription* other) {
  using std::swap;
  protoc_output_flag_.Swap(&other->protoc_output_flag_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  protoc_option_flag_.Swap(&other->protoc_option_flag_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata LanguageDescription::GetMetadata() const {
  protobuf_util_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_util_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

LanguageList_LanguagesEntry_DoNotUse::LanguageList_LanguagesEntry_DoNotUse() {}
LanguageList_LanguagesEntry_DoNotUse::LanguageList_LanguagesEntry_DoNotUse(::google::protobuf::Arena* arena) : SuperType(arena) {}
void LanguageList_LanguagesEntry_DoNotUse::MergeFrom(const LanguageList_LanguagesEntry_DoNotUse& other) {
  MergeFromInternal(other);
}
::google::protobuf::Metadata LanguageList_LanguagesEntry_DoNotUse::GetMetadata() const {
  ::protobuf_util_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_util_2eproto::file_level_metadata[4];
}
void LanguageList_LanguagesEntry_DoNotUse::MergeFrom(
    const ::google::protobuf::Message& other) {
  ::google::protobuf::Message::MergeFrom(other);
}


// ===================================================================

void LanguageList::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LanguageList::kLanguagesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LanguageList::LanguageList()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_util_2eproto::scc_info_LanguageList.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:google.protobuf.compiler.wasm.util.LanguageList)
}
LanguageList::LanguageList(const LanguageList& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  languages_.MergeFrom(from.languages_);
  // @@protoc_insertion_point(copy_constructor:google.protobuf.compiler.wasm.util.LanguageList)
}

void LanguageList::SharedCtor() {
}

LanguageList::~LanguageList() {
  // @@protoc_insertion_point(destructor:google.protobuf.compiler.wasm.util.LanguageList)
  SharedDtor();
}

void LanguageList::SharedDtor() {
}

void LanguageList::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* LanguageList::descriptor() {
  ::protobuf_util_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_util_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const LanguageList& LanguageList::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_util_2eproto::scc_info_LanguageList.base);
  return *internal_default_instance();
}


void LanguageList::Clear() {
// @@protoc_insertion_point(message_clear_start:google.protobuf.compiler.wasm.util.LanguageList)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  languages_.Clear();
  _internal_metadata_.Clear();
}

bool LanguageList::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:google.protobuf.compiler.wasm.util.LanguageList)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // map<string, .google.protobuf.compiler.wasm.util.LanguageDescription> languages = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          LanguageList_LanguagesEntry_DoNotUse::Parser< ::google::protobuf::internal::MapField<
              LanguageList_LanguagesEntry_DoNotUse,
              ::std::string, ::google::protobuf::compiler::wasm::util::LanguageDescription,
              ::google::protobuf::internal::WireFormatLite::TYPE_STRING,
              ::google::protobuf::internal::WireFormatLite::TYPE_MESSAGE,
              0 >,
            ::google::protobuf::Map< ::std::string, ::google::protobuf::compiler::wasm::util::LanguageDescription > > parser(&languages_);
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
              input, &parser));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            parser.key().data(), static_cast<int>(parser.key().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "google.protobuf.compiler.wasm.util.LanguageList.LanguagesEntry.key"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:google.protobuf.compiler.wasm.util.LanguageList)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:google.protobuf.compiler.wasm.util.LanguageList)
  return false;
#undef DO_
}

void LanguageList::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:google.protobuf.compiler.wasm.util.LanguageList)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // map<string, .google.protobuf.compiler.wasm.util.LanguageDescription> languages = 1;
  if (!this->languages().empty()) {
    typedef ::google::protobuf::Map< ::std::string, ::google::protobuf::compiler::wasm::util::LanguageDescription >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::google::protobuf::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "google.protobuf.compiler.wasm.util.LanguageList.LanguagesEntry.key");
      }
    };

    if (output->IsSerializationDeterministic() &&
        this->languages().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->languages().size()]);
      typedef ::google::protobuf::Map< ::std::string, ::google::protobuf::compiler::wasm::util::LanguageDescription >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::std::string, ::google::protobuf::compiler::wasm::util::LanguageDescription >::const_iterator
          it = this->languages().begin();
          it != this->languages().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::std::unique_ptr<LanguageList_LanguagesEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(languages_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            1, *entry, output);
        Utf8Check::Check(items[static_cast<ptrdiff_t>(i)]);
      }
    } else {
      ::std::unique_ptr<LanguageList_LanguagesEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::std::string, ::google::protobuf::compiler::wasm::util::LanguageDescription >::const_iterator
          it = this->languages().begin();
          it != this->languages().end(); ++it) {
        entry.reset(languages_.NewEntryWrapper(
            it->first, it->second));
        ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
            1, *entry, output);
        Utf8Check::Check(&*it);
      }
    }
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:google.protobuf.compiler.wasm.util.LanguageList)
}

::google::protobuf::uint8* LanguageList::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:google.protobuf.compiler.wasm.util.LanguageList)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // map<string, .google.protobuf.compiler.wasm.util.LanguageDescription> languages = 1;
  if (!this->languages().empty()) {
    typedef ::google::protobuf::Map< ::std::string, ::google::protobuf::compiler::wasm::util::LanguageDescription >::const_pointer
        ConstPtr;
    typedef ConstPtr SortItem;
    typedef ::google::protobuf::internal::CompareByDerefFirst<SortItem> Less;
    struct Utf8Check {
      static void Check(ConstPtr p) {
        ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          p->first.data(), static_cast<int>(p->first.length()),
          ::google::protobuf::internal::WireFormatLite::SERIALIZE,
          "google.protobuf.compiler.wasm.util.LanguageList.LanguagesEntry.key");
      }
    };

    if (deterministic &&
        this->languages().size() > 1) {
      ::std::unique_ptr<SortItem[]> items(
          new SortItem[this->languages().size()]);
      typedef ::google::protobuf::Map< ::std::string, ::google::protobuf::compiler::wasm::util::LanguageDescription >::size_type size_type;
      size_type n = 0;
      for (::google::protobuf::Map< ::std::string, ::google::protobuf::compiler::wasm::util::LanguageDescription >::const_iterator
          it = this->languages().begin();
          it != this->languages().end(); ++it, ++n) {
        items[static_cast<ptrdiff_t>(n)] = SortItem(&*it);
      }
      ::std::sort(&items[0], &items[static_cast<ptrdiff_t>(n)], Less());
      ::std::unique_ptr<LanguageList_LanguagesEntry_DoNotUse> entry;
      for (size_type i = 0; i < n; i++) {
        entry.reset(languages_.NewEntryWrapper(
            items[static_cast<ptrdiff_t>(i)]->first, items[static_cast<ptrdiff_t>(i)]->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       1, *entry, deterministic, target);
;
        Utf8Check::Check(items[static_cast<ptrdiff_t>(i)]);
      }
    } else {
      ::std::unique_ptr<LanguageList_LanguagesEntry_DoNotUse> entry;
      for (::google::protobuf::Map< ::std::string, ::google::protobuf::compiler::wasm::util::LanguageDescription >::const_iterator
          it = this->languages().begin();
          it != this->languages().end(); ++it) {
        entry.reset(languages_.NewEntryWrapper(
            it->first, it->second));
        target = ::google::protobuf::internal::WireFormatLite::
                   InternalWriteMessageNoVirtualToArray(
                       1, *entry, deterministic, target);
;
        Utf8Check::Check(&*it);
      }
    }
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:google.protobuf.compiler.wasm.util.LanguageList)
  return target;
}

size_t LanguageList::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:google.protobuf.compiler.wasm.util.LanguageList)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // map<string, .google.protobuf.compiler.wasm.util.LanguageDescription> languages = 1;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->languages_size());
  {
    ::std::unique_ptr<LanguageList_LanguagesEntry_DoNotUse> entry;
    for (::google::protobuf::Map< ::std::string, ::google::protobuf::compiler::wasm::util::LanguageDescription >::const_iterator
        it = this->languages().begin();
        it != this->languages().end(); ++it) {
      entry.reset(languages_.NewEntryWrapper(it->first, it->second));
      total_size += ::google::protobuf::internal::WireFormatLite::
          MessageSizeNoVirtual(*entry);
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void LanguageList::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:google.protobuf.compiler.wasm.util.LanguageList)
  GOOGLE_DCHECK_NE(&from, this);
  const LanguageList* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const LanguageList>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:google.protobuf.compiler.wasm.util.LanguageList)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:google.protobuf.compiler.wasm.util.LanguageList)
    MergeFrom(*source);
  }
}

void LanguageList::MergeFrom(const LanguageList& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:google.protobuf.compiler.wasm.util.LanguageList)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  languages_.MergeFrom(from.languages_);
}

void LanguageList::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:google.protobuf.compiler.wasm.util.LanguageList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LanguageList::CopyFrom(const LanguageList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:google.protobuf.compiler.wasm.util.LanguageList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LanguageList::IsInitialized() const {
  return true;
}

void LanguageList::Swap(LanguageList* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LanguageList::InternalSwap(LanguageList* other) {
  using std::swap;
  languages_.Swap(&other->languages_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata LanguageList::GetMetadata() const {
  protobuf_util_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_util_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace util
}  // namespace wasm
}  // namespace compiler
}  // namespace protobuf
}  // namespace google
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::google::protobuf::compiler::wasm::util::GeneratorInput* Arena::CreateMaybeMessage< ::google::protobuf::compiler::wasm::util::GeneratorInput >(Arena* arena) {
  return Arena::CreateInternal< ::google::protobuf::compiler::wasm::util::GeneratorInput >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::google::protobuf::compiler::wasm::util::GeneratorOutput_FilesEntry_DoNotUse* Arena::CreateMaybeMessage< ::google::protobuf::compiler::wasm::util::GeneratorOutput_FilesEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateInternal< ::google::protobuf::compiler::wasm::util::GeneratorOutput_FilesEntry_DoNotUse >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::google::protobuf::compiler::wasm::util::GeneratorOutput* Arena::CreateMaybeMessage< ::google::protobuf::compiler::wasm::util::GeneratorOutput >(Arena* arena) {
  return Arena::CreateInternal< ::google::protobuf::compiler::wasm::util::GeneratorOutput >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::google::protobuf::compiler::wasm::util::LanguageDescription* Arena::CreateMaybeMessage< ::google::protobuf::compiler::wasm::util::LanguageDescription >(Arena* arena) {
  return Arena::CreateInternal< ::google::protobuf::compiler::wasm::util::LanguageDescription >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::google::protobuf::compiler::wasm::util::LanguageList_LanguagesEntry_DoNotUse* Arena::CreateMaybeMessage< ::google::protobuf::compiler::wasm::util::LanguageList_LanguagesEntry_DoNotUse >(Arena* arena) {
  return Arena::CreateInternal< ::google::protobuf::compiler::wasm::util::LanguageList_LanguagesEntry_DoNotUse >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::google::protobuf::compiler::wasm::util::LanguageList* Arena::CreateMaybeMessage< ::google::protobuf::compiler::wasm::util::LanguageList >(Arena* arena) {
  return Arena::CreateInternal< ::google::protobuf::compiler::wasm::util::LanguageList >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
